#include "NEXUS.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, NEXUS, "NEXUS");

DEFINE_LOG_CATEGORY(LogNEXUS);
DEFINE_LOG_CATEGORY(LogNexusMatch);
DEFINE_LOG_CATEGORY(LogNexusRound);
DEFINE_LOG_CATEGORY(LogNexusNetwork);
DEFINE_LOG_CATEGORY(LogNexusWeapon);
DEFINE_LOG_CATEGORY(LogNexusBomb);
DEFINE_LOG_CATEGORY(LogNexusBot);
DEFINE_LOG_CATEGORY(LogNexusNav);
DEFINE_LOG_CATEGORY(LogNexusEconomy);
DEFINE_LOG_CATEGORY(LogNexusOperator);
DEFINE_LOG_CATEGORY(LogNexusArt);
